"""init tables

Revision ID: 6ef2f56f7bc6
Revises: e6e52c3212f0
Create Date: 2025-12-16 23:50:48.204976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef2f56f7bc6'
down_revision: Union[str, Sequence[str], None] = 'e6e52c3212f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('property_ward_fkey'), 'property', type_='foreignkey')
    op.drop_constraint(op.f('property_province_fkey'), 'property', type_='foreignkey')
    op.drop_constraint(op.f('property_district_fkey'), 'property', type_='foreignkey')
    op.create_foreign_key(None, 'property', 'district', ['district_id'], ['id'])
    op.create_foreign_key(None, 'property', 'province', ['province_id'], ['id'])
    op.create_foreign_key(None, 'property', 'ward', ['ward_id'], ['id'])
    op.drop_column('property', 'ward')
    op.drop_column('property', 'district')
    op.drop_column('property', 'province')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('province', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('district', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('ward', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key(op.f('property_district_fkey'), 'property', 'district', ['district'], ['id'])
    op.create_foreign_key(op.f('property_province_fkey'), 'property', 'province', ['province'], ['id'])
    op.create_foreign_key(op.f('property_ward_fkey'), 'property', 'ward', ['ward'], ['id'])
    op.drop_column('property', 'ward_id')
    op.drop_column('property', 'district_id')
    op.drop_column('property', 'province_id')
    # ### end Alembic commands ###
