"""table(user): add field super user

Revision ID: a88963f7dce4
Revises: 712ab2ddb0c6
Create Date: 2025-12-05 22:05:37.716968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88963f7dce4'
down_revision: Union[str, Sequence[str], None] = '712ab2ddb0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('super_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    # 2. Gán giá trị default cho dữ liệu cũ
    op.execute('UPDATE "user" SET super_user = FALSE WHERE super_user IS NULL')

    # 3. Set NOT NULL
    op.alter_column('user', 'super_user', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'super_user')
    # ### end Alembic commands ###
